### model
model_name_or_path: /root/autodl-fs/models/Qwen/Qwen2-VL-2B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
# deepspeed: examples/ds_config/zero2_offload.json

### dataset
dataset: ali_tianchi_vision
template: qwen2_vl
cutoff_len: 20480
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /root/autodl-tmp/projects/LLaMA-Factory/saves/qwen2_vl-2b/full/sft_train_20241128_01
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
save_total_limit: 3
